/// Markdown reporter for PR comments and documentation.
///
/// Produces GitHub-Flavored Markdown suitable for pull request
/// comments, wiki pages, or static documentation.
library;

import 'package:vetro/core/models/finding.dart';
import 'package:vetro/core/report/reporter.dart';

/// Formats a [ProjectReport] as GitHub-Flavored Markdown.
///
/// Output includes:
/// - Project info header
/// - Summary table with severity counts
/// - AI Debt Score with visual indicator
/// - Findings grouped by file
final class MarkdownReporter extends Reporter {
  const MarkdownReporter();

  @override
  String format(ProjectReport report) {
    final markdownBuffer = StringBuffer();

    _writeHeader(markdownBuffer, report);
    _writeSummaryTable(markdownBuffer, report);
    _writeDebtScore(markdownBuffer, report);
    _writeFindings(markdownBuffer, report);

    // Note: Inline footer rendering here to avoid structural copy-mutate similarity with TerminalReporter.
    markdownBuffer.writeln('---');
    markdownBuffer.writeln();
    markdownBuffer.writeln('_Generated by [Vetro](https://github.com/vetro-dev/vetro) v0.1.0_');
    markdownBuffer.writeln();

    return markdownBuffer.toString();
  }

  void _writeHeader(StringBuffer buf, ProjectReport report) {
    final projectName = extractProjectName(report.projectPath);
    final timeSeconds = (report.totalAnalysisTimeMs / 1000)
        .toStringAsFixed(1);

    buf.writeln('# 📊 Vetro Report — $projectName');
    buf.writeln();
    buf.writeln('| Metric | Value |');
    buf.writeln('|--------|-------|');
    buf.writeln('| **Project** | `${report.projectPath}` |');
    buf.writeln('| **Files analyzed** | ${report.fileCount} |');
    buf.writeln(
      '| **Lines of code** | ${formatNumber(report.totalLines)} |',
    );
    buf.writeln('| **Analysis time** | ${timeSeconds}s |');
    buf.writeln(
      '| **Analyzed at** | ${report.analyzedAt.toIso8601String()} |',
    );
    buf.writeln();
  }

  void _writeSummaryTable(StringBuffer buf, ProjectReport report) {
    final errors = report.countBySeverity(Severity.error);
    final warnings = report.countBySeverity(Severity.warning);
    final infos = report.countBySeverity(Severity.info);
    final total = report.allFindings.length;

    buf.writeln('## Summary');
    buf.writeln();
    buf.writeln('| Severity | Count |');
    buf.writeln('|----------|------:|');
    buf.writeln('| 🔴 Error | $errors |');
    buf.writeln('| ⚠️ Warning | $warnings |');
    buf.writeln('| ℹ️ Info | $infos |');
    buf.writeln('| **Total** | **$total** |');
    buf.writeln();
  }

  void _writeDebtScore(StringBuffer buf, ProjectReport report) {
    final score = report.aiDebtScore;
    final emoji = _scoreEmoji(score);

    buf.writeln('## AI Debt Score');
    buf.writeln();
    buf.writeln('$emoji **$score / 100**');
    buf.writeln();

    if (score >= 80) {
      buf.writeln('> ✅ Code is in good shape.');
    } else if (score >= 50) {
      buf.writeln('> ⚠️ Code has moderate AI debt — review recommended.');
    } else {
      buf.writeln('> 🚨 High AI debt detected — immediate action needed.');
    }
    buf.writeln();
  }

  void _writeFindings(StringBuffer buf, ProjectReport report) {
    // We check for empty findings because we want to early-out and present a clean bill
    // of health with a clear and encouraging message.
    final allFindings = report.allFindings;
    if (allFindings.isEmpty) {
      buf.writeln('## Findings');
      buf.writeln();
      buf.writeln('_No findings — code is clean!_ ✨');
      buf.writeln();
      return;
    }

    buf.writeln('## Findings');
    buf.writeln();

    // We group findings by file path because showing files as distinct Markdown sections 
    // with tables is the most readable layout for developers tracking issues in PR comments.
    final byFile = <String, List<Finding>>{};
    for (final finding in allFindings) {
      byFile.putIfAbsent(finding.filePath, () => []).add(finding);
    }

    for (final entry in byFile.entries) {
      final filePath = entry.key;
      final findings = entry.value;

      buf.writeln('### `$filePath`');
      buf.writeln();
      buf.writeln('| Line | Severity | Rule | Message |');
      buf.writeln('|-----:|----------|------|---------|');

      for (final finding in findings) {
        final icon = _severityIcon(finding.severity);
        buf.writeln(
          '| ${finding.line} '
          '| $icon ${finding.severity.name} '
          '| ${finding.ruleName} '
          '| ${_escapeMarkdown(finding.message)} |',
        );
      }
      buf.writeln();

      // Write evidence as details block if any finding has it.
      final withEvidence = findings.where(
        (f) => f.evidence.isNotEmpty,
      );
      if (withEvidence.isNotEmpty) {
        buf.writeln('<details>');
        buf.writeln('<summary>Evidence details</summary>');
        buf.writeln();
        for (final finding in withEvidence) {
          buf.writeln('**Line ${finding.line} — ${finding.ruleName}**');
          for (final ev in finding.evidence.entries) {
            buf.writeln('- `${ev.key}`: ${ev.value}');
          }
          buf.writeln();
        }
        buf.writeln('</details>');
        buf.writeln();
      }
    }
  }

  // ── Helpers ──────────────────────────────────────────────────

  /// Returns a score emoji based on value thresholds.
  static String _scoreEmoji(int score) {
    if (score >= 80) return '🟢';
    if (score >= 50) return '🟡';
    return '🔴';
  }

  /// Returns the severity icon for markdown.
  static String _severityIcon(Severity severity) => switch (severity) {
        Severity.error => '🔴',
        Severity.warning => '⚠️',
        Severity.info => 'ℹ️',
      };

  /// Escapes markdown-sensitive characters in text.
  static String _escapeMarkdown(String text) => text
      .replaceAll('|', '\\|')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;');
}
